# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arayuz.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(407, 304)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(30, 10, 351, 251))
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.btn_sec = QtWidgets.QPushButton(self.groupBox)
        self.btn_sec.setGeometry(QtCore.QRect(10, 60, 81, 31))
        self.btn_sec.setObjectName("btn_sec")
        self.lbl_resim = QtWidgets.QLabel(self.groupBox)
        self.lbl_resim.setGeometry(QtCore.QRect(120, 10, 221, 171))
        self.lbl_resim.setObjectName("lbl_resim")
        self.lbl_sayi = QtWidgets.QLabel(self.groupBox)
        self.lbl_sayi.setGeometry(QtCore.QRect(120, 190, 221, 31))
        self.lbl_sayi.setObjectName("lbl_sayi")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 407, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Hücre Sayım Programı"))
        self.btn_sec.setText(_translate("MainWindow", "Fotoğraf Seç"))
        self.lbl_resim.setText(_translate("MainWindow", "        Resim burada gösterilecek"))
        self.lbl_sayi.setText(_translate("MainWindow", "  Hücre Sayısı: "))
